name: Deploy it on two different machines

on:
  push:
    branches:
      - main

jobs:
  remote_deploy:
    runs-on: [self-hosted, aminlodhi]
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker-compose down || true
          docker-compose build
          docker-compose up -d
